architecture: FCOS
max_iters: 18000
use_gpu: true
snapshot_iter: 2000
log_smooth_window: 20
log_iter: 20
save_dir: output
pretrain_weights: pretrain/ShuffleNetV2_x0_5_pretrained
metric: COCO
weights: output/fcos_r50_fpn_1x/model_final
num_classes: 2

FCOS:
  backbone: ShuffleNetV2
  fpn: FPNLite
  fcos_head: FCOSLiteHead

ShuffleNetV2:
  conv_group_scale: 0.5
  norm_decay: 0
  freeze_norm: false
  norm_decay: 0.
  feature_maps: [3, 4, 5]

FPNLite:
  min_level: 3
  max_level: 7
  num_chan: 128
  use_c5: false
  spatial_scale: [0.03125, 0.0625, 0.125]
  has_extra_convs: true

FCOSLiteHead:
  num_classes: 2
  fpn_stride: [8, 16, 32, 64, 128]
  num_convs: 4
  norm_type: "bn"
  prior_prob: 0.1
  fcos_loss: FCOSLoss
  norm_reg_targets: True
  centerness_on_reg: True
  use_dcn_in_tower: False
  nms: MultiClassNMS

MultiClassNMS:
  score_threshold: 0.025
  nms_top_k: 100
  keep_top_k: 100
  nms_threshold: 0.6
  background_label: -1

FCOSLoss:
  loss_alpha: 0.75
  loss_gamma: 2.0
  iou_loss_type: "giou"
  reg_weights: 2.0

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [12000, 16000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.000001
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score', 'im_info']
  dataset:
    !COCODataSet
    image_dir: images
    anno_path: annotations/dumix_finger_point_location_boundingbox_train.json
    dataset_dir: dataset/dumix_finger_point
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 192
    max_size: 256
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 16
    use_padded_im_info: false
  - !Gt2FCOSTarget
    object_sizes_boundary: [32, 64, 96, 128]
    center_sampling_radius: 1.5
    downsample_ratios: [8, 16, 32, 64, 128]
    norm_reg_targets: True
  batch_size: 16
  shuffle: true
  worker_num: 16
  use_process: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_id', 'im_shape', 'im_info']
  dataset:
    !COCODataSet
    image_dir: images
    anno_path: annotations/dumix_finger_point_location_boundingbox_191227_test.json
    dataset_dir: dataset/dumix_finger_point
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: 192
    max_size: 256
    interp: 1
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 16
    use_padded_im_info: true
  batch_size: 2
  shuffle: false
  worker_num: 2
  use_process: false

TestReader:
  inputs_def:
    # set image_shape if needed
    fields: ['image', 'im_id', 'im_shape', 'im_info']
  dataset:
    !ImageFolder
    anno_path: annotations/instances_val2017.json
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 256
    target_size: 192
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 16
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
