architecture: TTFNet
use_gpu: true
max_iters: 150000
log_smooth_window: 20
save_dir: output
snapshot_iter: 1000
metric: COCO
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV3_small_x0_35_pretrained.tar
weights: output/ttfnet_mobilenetv3/model_final
num_classes: 2

TTFNet:
  backbone: MobileNetV3RCNN
  ttf_head: TTFLiteHead

MobileNetV3RCNN:
  norm_type: "bn"
  norm_decay: 0.0
  model_name: small
  scale: 0.35
  feature_maps: [2,3,4,5]
  conv_decay: 0.00001
  lr_mult_list: [0.25, 0.25, 0.5, 0.5, 0.75]

TTFLiteHead:
  head_conv: 40
  planes: [80, 40, 20]
  shortcut_num: [1, 1, 1]
  wh_head_conv_num: 1
  hm_head_conv_num: 1

GiouLoss:
  loss_weight: 5.
  do_average: false
  use_class_weight: false

LearningRate:
  base_lr: 0.002 #0.015
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 120000 #112500
    - 140000 #137500
  - !LinearWarmup
    start_factor: 0.2
    steps: 1000

OptimizerBuilder:
  #clip_grad_by_norm: 35
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.00001
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight']
    image_shape: [3, 160, 160]
  dataset:
    !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !KeepRatio
    aspect_ratio: 1.7778
    training: true
  - !Resize
    target_dim: 160
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
  - !Permute
    to_bgr: false
    channel_first: true
  - !TTFTarget
    output_size: 160
    num_classes: 2
    down_ratio: 4
  batch_transforms:
  - !PadBatch
    pad_to_stride: 16
  batch_size: 32
  shuffle: true
  worker_num: 16
  bufsize: 32
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_id', 'scale_factor']
    image_shape: [3, 160, 160]
  dataset:
    !COCODataSet
      image_dir: val2017
      anno_path: annotations/instances_val2017.json
      dataset_dir: dataset/coco
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      target_dim: 160
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 4
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3, 160, 160]
    fields: ['image', 'im_id', 'scale_factor']
  dataset:
    !ImageFolder
      anno_path: annotations/instances_val2017.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      interp: 1
      target_dim: 160
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
