architecture: TTFNet
use_gpu: true
max_iters: 75000
log_smooth_window: 20
save_dir: output
snapshot_iter: 5000
metric: COCO
pretrain_weights: pretrain/ShuffleNetV2_x0_5_pretrained
weights: output/ttfnet_shufflenetV2/model_final
num_classes: 2

TTFNet:
  backbone: ShuffleNetV2
  ttf_head: TTFLiteHead

ShuffleNetV2:
  conv_group_scale: 0.5
  norm_decay: 0
  freeze_norm: false
  feature_maps: [1, 2, 3, 4, 5]

TTFLiteHead:
  head_conv: 192
  wh_conv: 96
  planes: [192, 192, 96]
  hm_head_conv_num: 2
  wh_head_conv_num: 2
  wh_offset_base: 16
  wh_loss: GiouLoss

GiouLoss:
  loss_weight: 5.
  do_average: false
  use_class_weight: false

LearningRate:
  base_lr: 0.05
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 56250
    - 68750
  - !LinearWarmup
    start_factor: 0.2
    steps: 500

OptimizerBuilder:
  #clip_grad_by_norm: 35
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0004
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'ttf_heatmap', 'ttf_box_target', 'ttf_reg_weight']
    image_shape: [3, 224, 224]
  dataset:
    !COCODataSet
    dataset_dir: dataset/dumix_finger_point
    anno_path: annotations/dumix_finger_point_location_boundingbox_train.json
    image_dir: images
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !Resize
    target_dim: 224
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: false
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
  - !Permute
    to_bgr: false
    channel_first: true
  - !TTFTarget
    output_size: 224
    num_classes: 2
    down_ratio: 4
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  batch_size: 32
  shuffle: true
  worker_num: 16
  bufsize: 32
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_id', 'scale_factor']
    image_shape: [3, 224, 224]
  dataset:
    !COCODataSet
      dataset_dir: dataset/dumix_finger_point
      anno_path: annotations/dumix_finger_point_location_boundingbox_test.json
      image_dir: images
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      target_dim: 224
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 8
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3, 224, 224]
    fields: ['image', 'im_id', 'scale_factor']
  dataset:
    !ImageFolder
      dataset_dir: dataset/dumix_finger_point
      anno_path: annotations/dumix_finger_point_location_boundingbox_test.json
      image_dir: images
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !Resize
      interp: 1
      target_dim: 224
    - !NormalizeImage
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      is_scale: false
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
